Serialize System components to HDF5
NREL-Sienna/PowerSimulations.jl pull request #1062
Opened 2024-02-26 22:44 UTC by daniel-thom

Objective: The simulations postprocessing code in PowerAnalytics.jl needs to have access to the systems used by the simulations. Those systems are not serialized if the user opts out of that feature. Ensure that these are always available.

This is the PowerSimulations portion of the solution. I added comparable branches in PowerSystems.jl and InfrastructureSystems.jl. Let me know if the interfaces here meet your needs and then I’ll open sibling PRs.

2024-02-26 22:47 UTC, daniel-thom commented on test/test_simulation_results.jl
> +@testset "Test simulation results with system from store" begin
The changes in this file are minor. I had to shuffle things around so that I could test the new code here.

2024-02-28 18:40 UTC, GabrielKS requested changes
Looks pretty good to me besides the comment about the `get_system!` kwarg.

2024-02-29 16:50 UTC, jd-lara approved these changes

2024-02-29 16:51 UTC, jd-lara commented
@daniel-thom run the formatter to merge

2024-02-29 18:40 UTC, daniel-thom commented
> @daniel-thom run the formatter to merge

Done

2024-02-29 18:41 UTC, merged